export interface Cliente {
  idCliente: number;
  idGenero: number;
  idEstadoCivil: number;
  idClienteSituacao: number;
  clienteSituacao: string;
  cpf: string;
  rg: string;
  nome: string;
  dataNascimento: string;
  peso: number;
  altura: number;
  telFixo: string;
  telCel: string;
  nomeContato: string;
  endereco: string;
  numero: number;
  complemento: string;
  municipio: string;
  estado: string;
  uf: string;
  cep: string;
  pais: string;
  coordenadas: string;
  latitude: string;
  longitude: string;
  obs: string;
  dtInsert: string;
}
